config/routes.rb
Rails.application.routes.draw do

  
  resources :babblers, only:[:index, :new, :create, :edit, :update, :destroy] do
    collection do
      post :confirm
    end
  end
  
  root'top#index'
  

end

app/models/babbler.rb
class Babbler < ActiveRecord::Base
    validates:content, length:{minimum: 1}
    validates:content, length:{maximum: 140}
    validates:content, presence:true
end

    
      

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/babblers_controller.rb
class BabblersController < ApplicationController
  before_action :set_babbler, only:[:edit, :update, :destroy]
  
  def index
    @babblers = Babbler.all.order(id: :desc)
  end

  def new
    if params[:back]
      @babbler = Babbler.new(babblers_params)
    else
    @babbler = Babbler.new
    end
  end
  
  def create
    @babbler = Babbler.create(babblers_params)
    if @babbler.save
      redirect_to babblers_path, notice:'Your Babble has been created'
    else
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @babbler.update(babblers_params)
      redirect_to babblers_path, notice:'Your Babbler has been updated'
    else
      render'edit'
    end
  end
  
  def destroy
    @babbler.destroy
    redirect_to babblers_path, notice:'Your Babble has been deleted'
  end

  def confirm
    @babbler= Babbler.new(babblers_params)
    render :new if @babbler.invalid?
  end

private 
  def babblers_params
    params.require(:babbler).permit(:title, :content)
  end
  
  def set_babbler
    @babbler = Babbler.find(params[:id])
  end


end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/babblers_helper.rb
module BabblersHelper
  def choose_new_or_edit
    if action_name == 'new' 
      confirm_babblers_path
    elsif action_name == 'edit'
      babbler_path
    end
  end    
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/babblers/_form.html.erb
<p id= "notice"><%= notice %></p>

<%= form_for(@babbler, url:choose_new_or_edit)do |f| %>
  <% if @babbler.errors.any? %>
    <div id="error_explanation">
      <h2><%= @babbler.errors.count %>errors has been detected!!</h2>
      <ul>
      <% @babbler.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <br>
  <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <br>
  <%= f.submit "Create", class:'btn btn-primary '%>
  <br>
<% end %>
<br>

app/views/babblers/confirm.html.erb
<div class="container">
  <div class="col-md-8 col-md-offset-2 col-sm-10">
    <h1>Are you sure to send?</h1>
    <%= form_for(@babbler) do |f| %>
      <%= f.hidden_field :content %>
      <p>Content:<%=@babbler.content %></p>
      <%= f.submit "Comfirm", class:'btn btn-primary'%>
    <% end %>
    <%= form_for(@babbler, url:new_babbler_path, method:'get') do |f| %>
      <%= f.hidden_field :content %>
      <%= f.submit "Back", name:'back', class: 'btn btn-default'%>
    <% end %>
  </div>
</div>

app/views/babblers/edit.html.erb
<div class="container">
  <p><%= notice %></p>
    <div class="col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1">
      <%= render 'form' %>
      <%= link_to "Back to Timeline", babblers_path %>
    </div>  
</div>

app/views/babblers/index.html.erb
<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
    <h1>Timeline</h1>
    <p><%= notice %></p>
    <div class="create"><%= link_to "Make a Babble", new_babbler_path, class:"square_btn btn-lg" %></div>
    <br>
      <% @babblers.each do |babbler| %>
      <div class= "row">
        <div class= "panel panel-default">
          <div class="panel-body">
            <h4><strrong><%= babbler.content %></strrong></h4>
            <%= link_to "Edit", edit_babbler_path(babbler.id), class: 'btn btn-default btn-sm'%>
            <%= link_to "Delete", babbler_path(babbler.id), method: :delete, data:{confirm: 'Are you sure to delete?' }, class: 'btn btn-default btn-sm' %>
          </div>
        </div>
      </div>
      <% end %>
      <br>
      <br>
      <div class="row col-md-2 col-md-offset-10 col-sm-10">
        <%= link_to "Back to Top", root_path, class: "btn_normal btn-md" %>
      </div>
  </div>
</div>

app/views/babblers/new.html.erb
<div class="container">
  <div class="col-md-8 col-md-offset-2 col-sm-10">
  <h1>What do you babble?</h1>
    <%= render 'form' %>
    <div class="row col-md-2 col-md-offset-10 col-sm-10">
    <%= link_to "Back to Timeline", babblers_path, class: "btn_normal btn-md"%>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Babbler</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>
  <header>

    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <!-- <div>はブロック要素に対して使用され、<span>はインライン要素に対して使用される -->
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%# <ul style="list-style:none;"> %>
          <%= link_to "Babbles", new_babbler_path, class:"navbar-brand" %>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Top", root_path %></li>
            <li><%= link_to "Timeline", babblers_path %></li>

          </ul>
        </div>
          
      </div>
    </nav>
  </header>

<%= yield %>

    <footer>
      <p>株式会社ABC</p>
      <p>© 2015-2017 Copyright ABC Corp</p>
    </footer>
    
</body>
</html>

app/views/top/index.html.erb
<!-- Babblers#index -->
<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
  <h1>Babblers</h1>
    <div class="box">
        <p>Here is a place that you can babbler anything what you come up in your mind.</p>
        <p><br>
          Writing just your feelings,<br>
          something you don’t need to tell to someone,<br>
          complains you have, sharing your small happinesses in your daily life.</p><br>
        <p>You don’t expect someone to care.<br>
          but if you can get a small attention, you feel “ it is not bad ”.<br><br>
          Here is that kinf of place you can babble.</p>
          
    </div>
  </div>
</div>


<div class="row col-md-8 col-md-offset-4">
<div class="unq_btn2",>
<!--以下twitter-->
<a href="#">
  <span class="fa-stack">
    <i class="fa fa-tablet fa-stack-2x"></i>
    <i class="fa fa-twitter fa-stack-1x"></i>
  </span>
</a>
<!--以下facebook-->
<a href="#">
  <span class="fa-stack">
    <i class="fa fa-tablet fa-stack-2x"></i>
    <i class="fa fa-facebook fa-stack-1x"></i>
  </span>
</a>
<!--以下feedly-->
<a href="#">
  <span class="fa-stack">
    <i class="fa fa-tablet fa-stack-2x"></i>
    <i class="fa fa-rss fa-stack-1x"></i>
  </span>
</a>
<!--以下pocket-->
<a href="#">
   <span class="fa-stack">
    <i class="fa fa-tablet fa-stack-2x"></i>
    <i class="fa fa-get-pocket fa-stack-1x"></i>
  </span>
</a>
<!--以下google plus-->
<a href="#">
   <span class="fa-stack">
    <i class="fa fa-tablet fa-stack-2x"></i>
    <i class="fa fa-google-plus fa-stack-1x"></i>
  </span>
</a>
</div>
</div>